### ISSUE TITLE
Hitting an error

### ISSUE THREAD

**Issue by akaAMAZING** [delusionx/PoESniper#1]
Followed instructions exactly. Using Python 3.7.5.

Please refer to the screenshot below:

http://prntscr.com/pnwwtn

**Comment by infernumx** [comment]
Can you show me what your config.json looks like? It looks like you have an extra comma after a value, so the parser expects another key:value pair but you don't have one.

**Comment by akaAMAZING** [comment]
Oh gotcha. I have since fixed that extra comma. Now I see this:

http://prntscr.com/po6uw2

(top command shows the previous error. bottom command shows the new error after fixing the first)

**Comment by akaAMAZING** [comment]
Nevermind the comment above, seemed to have fixed the problem by:

lib\site-packages\tzlocal\win32.py

#utils.assert_tz_offset(_cache_tz)

Shall test everything out now it's working.
