### ISSUE TITLE
Hi again!

### ISSUE THREAD

**Issue by akaAMAZING** [delusionx/PoESniper#4]
As a long time user of this program, upon returning to POE I am saddened to find that this is not working anymore. It was a godsend as it used to allow me to purchase items in bulk for crafting purposes.

Any idea if you will be continuing this project? I'd like to buy you a coffee if so!

Thank you

**Comment by infernumx** [comment]
> As a long time user of this program, upon returning to POE I am saddened to find that this is not working anymore. It was a godsend as it used to allow me to purchase items in bulk for crafting purposes.
> 
> Any idea if you will be continuing this project? I'd like to buy you a coffee if so!
> 
> Thank you

I have a private working GUI version, this project was barebones & the beginning, this repo is only public for display.
If you'd like to contact me about the GUI version you can add me on Discord and I can showcase it for you `garlic bread#0001`.
